-- Branch address and pin_location updates
-- Source: BRANCH ADDRESS PIN CONTACT.xlsx
-- 4 branches skipped (no data): LAS PIÑAS, NAIC CAVITE, PARAÑAQUE, STA MARIA

UPDATE branches SET address = '1809 P. De Guzman Street, 3rd gate marisol Angeles, Pampanga', pin_location = 'https://maps.app.goo.gl/mqZdgXhHHaTxFNWCA' WHERE name ILIKE '%ANGELES%';
UPDATE branches SET address = 'Brgy Sta Cruz Gumamela 1 Antipolo', pin_location = 'https://maps.app.goo.gl/ANeprHcuv9N5PSyt6' WHERE name ILIKE '%ANTIPOLO%';
UPDATE branches SET address = '1124 BLDG. HILOT CENTER MC. ARTHUR HIGHWAY, SAMPALOC APALIT PAMPANGA', pin_location = 'https://maps.app.goo.gl/YiX9kD6rHtcEXWcW7' WHERE name ILIKE '%APALIT%';
UPDATE branches SET address = 'Unit No. 1 Lot 33-A Pedrosa Subd., Circumferential Road Alijis, Negros Occidental', pin_location = 'https://maps.app.goo.gl/bMxp93ZYWmy66BKb6' WHERE name ILIKE '%BACOLOD%';
UPDATE branches SET address = '113 P.F.Espiritu Andrea Village2 Panapaan IV, Bacoor City Cavite', pin_location = 'https://maps.app.goo.gl/ihLJkLjdYjp7eaLZ6' WHERE name ILIKE '%BACOOR%';
UPDATE branches SET address = 'Phase 9, Langit Road, Bagong Silang, Caloocan City', pin_location = 'https://maps.app.goo.gl/ftSLHnXjg8fj8gRn6' WHERE name ILIKE '%BAGONG SILANG%';
UPDATE branches SET address = '316 Magsaysay Avenue Purok 3 Baranggay Lower Baguio City Philippines', pin_location = 'https://maps.app.goo.gl/iMw9vAGX1ymsF9kJ6' WHERE name ILIKE '%BAGUIO%';
UPDATE branches SET address = 'Uni Capital Corp., 124 MacArthur Hwy, Balagtas, 3016 Bulakan', pin_location = 'https://maps.app.goo.gl/AmJfD4UB77TqGFPU6' WHERE name ILIKE '%BALAGTAS%';
UPDATE branches SET address = 'BS Aquino Avenue Bagong Nayon Baliuag City Bulacan', pin_location = 'https://maps.app.goo.gl/HKBNgm8wCJthpBKQ9' WHERE name ILIKE '%BALIUAG%';
UPDATE branches SET address = '6 Fernandez Building Circumferential Road Barangay DS Garcia', pin_location = 'https://maps.app.goo.gl/9Jbd8M95Ks84t41P9' WHERE name ILIKE '%CABANATUAN%';
UPDATE branches SET address = '47 P. Burgos St. Barangay 3 Calamba Laguna', pin_location = 'https://maps.app.goo.gl/RPtCaQwUFGRpC2PU8' WHERE name ILIKE '%CALAMBA%';
UPDATE branches SET address = 'Purok Uno Liwanag Street Brgy Iglesia Cardona Rizal', pin_location = 'https://waze.com/ul/hwdw4qtj2j' WHERE name ILIKE '%CARDONA%';
UPDATE branches SET address = 'RGY Building, J. De Veyra Street, Brgy Carreta, Cebu City', pin_location = 'https://waze.com/ul/hwcb4esxue' WHERE name ILIKE '%CEBU CITY%';
UPDATE branches SET address = 'M.H Del Pilar Dagupan City, Pangasinan', pin_location = 'https://maps.app.goo.gl/zhYMcWTFveJQiuG57' WHERE name ILIKE '%DAGUPAN%';
UPDATE branches SET address = 'Arjemm Building, Blk J-1 Lot 9 & 10 Brgy. San Francisco 2, 4115 Dasmariñas', pin_location = 'https://maps.app.goo.gl/GqfQu6Xtzpk64ZWp9' WHERE name ILIKE '%DASMA%';
UPDATE branches SET address = 'Brgy. San Vicente Delos Reyes St.', pin_location = 'https://maps.app.goo.gl/Rpxuu8GHacMqinm49' WHERE name ILIKE '%GAPAN%';
UPDATE branches SET address = '257 Arnaldo hiway, PASCAM 1 Pasong camachille 1, General trias, Cavite', pin_location = 'https://maps.app.goo.gl/qPazv21kxrRmJH9p7' WHERE name ILIKE '%GENERAL TRIAS%';
UPDATE branches SET address = 'Blk 11 Lot 4 Carmen J. Ledesma Village, Tacas Jaro, Iloilo City', pin_location = 'https://maps.app.goo.gl/Vd1nqsbYWNxW3wmR9' WHERE name ILIKE '%ILOILO%';
UPDATE branches SET address = '28 Advincula Rd, Imus, 4103 Cavite', pin_location = 'https://maps.app.goo.gl/9e6LecsfcS6jGqpw6' WHERE name ILIKE '%IMUS%';
UPDATE branches SET address = 'Marsman T. Alvarez Boulevard, Fourlanes Road, Santiago City, Isabela', pin_location = 'https://maps.app.goo.gl/i9bHjaqmKH8nGuCy5' WHERE name ILIKE '%SANTIAGO%' AND name ILIKE '%ISABELA%';
UPDATE branches SET address = '3 Castro building K-1st Luis Shanghio St. Kamuning Quezon City', pin_location = 'https://maps.app.goo.gl/JfxUXqFfzfyqfWUM6' WHERE name ILIKE '%KAMUNING%';
UPDATE branches SET address = 'Quirino Highway, Corner Kaypian Rd', pin_location = 'https://waze.com/ul/hwdwh709sm' WHERE name ILIKE '%KAYPIAN%';
UPDATE branches SET address = 'P. Rodriguez St. Tiangue Road Looc Lapu Lapu City', pin_location = 'https://maps.app.goo.gl/EhFtyUmYdmXFobsU8' WHERE name ILIKE '%LAPU%';
UPDATE branches SET address = '10 Km 4 La Trinidad Infront Jewels Igorot Building', pin_location = 'https://maps.app.goo.gl/PsiJwnBkuu6bduNx5' WHERE name ILIKE '%LA TRINIDAD%';
UPDATE branches SET address = '169 Balintawak Road Barangay Balintawak Lipa Batangas', pin_location = 'https://maps.app.goo.gl/CaHvL5SgUy9LGCx48' WHERE name ILIKE '%LIPA%';
UPDATE branches SET address = 'Mabiga Mabalacat Pampanga Taitafalcom Unit 5', pin_location = 'https://maps.app.goo.gl/vjMLQ55zGFXreHPV6' WHERE name ILIKE '%MABALACAT%';
UPDATE branches SET address = '285 Cm Del Pilar St Brgy. Maysil Malabon', pin_location = 'https://maps.app.goo.gl/BiEAcbf94FFDEnQe8' WHERE name ILIKE '%MALABON%';
UPDATE branches SET address = 'The Royal Plaza Twin Tower Condominiums', pin_location = 'https://maps.app.goo.gl/nfTpxunxiCwH29jG6' WHERE name ILIKE '%MALATE%';
UPDATE branches SET address = 'Fernando Building Blas Ople Road Bulihan Malolos City, Bulacan', pin_location = 'https://maps.app.goo.gl/nSawpDVq5ZNkzXBM6' WHERE name ILIKE '%MALOLOS%';
UPDATE branches SET address = 'Marilao, Hilot Center, Lias RD, Marilao, 3019 Bulacan', pin_location = 'https://maps.app.goo.gl/a6aYAyzampVpMmfv5' WHERE name ILIKE '%MARILAO%';
UPDATE branches SET address = '721, 1800 J.P Rizal St. Marikina, 1800 Metro Manila', pin_location = 'https://maps.app.goo.gl/qLGgTPhhYmTZC4eC9' WHERE name ILIKE '%MARIKINA%';
UPDATE branches SET address = '3020 El Camino Real St. Cor. Apt drv Unit 004', pin_location = 'https://maps.app.goo.gl/FMgjChZi8CG1Co1J9' WHERE name ILIKE '%MEYCAUAYAN%';
UPDATE branches SET address = '51 A.Mabini Street Burgos Montalban Rizal', pin_location = 'https://maps.app.goo.gl/4sqVqCdSNuqeF43SA' WHERE name ILIKE '%MONTALBAN%';
UPDATE branches SET address = 'El Rancho Tunasan', pin_location = 'https://maps.app.goo.gl/LM3nj1gLha3BXNpG7' WHERE name ILIKE '%MUNTINLUPA%';
UPDATE branches SET address = 'TNC Muzon, SJDM, Bulacan', pin_location = 'https://maps.app.goo.gl/Nq1bdy9wKsxfPAfw6' WHERE name ILIKE '%MUZON%';
UPDATE branches SET address = 'F. Castro Corner Escalera St. Nasugbu Batangas', pin_location = 'https://maps.app.goo.gl/REStSF6bBty5b6hX7' WHERE name ILIKE '%NASUGBU%';
UPDATE branches SET address = 'Reylilia Building Commonwealth Fairview', pin_location = 'https://maps.app.goo.gl/bURXMft2zCRPzBek8' WHERE name ILIKE '%NORTH FAIRVIEW%';
UPDATE branches SET address = 'Traveleona 2go Crossing, A. Payumo Street', pin_location = 'https://maps.app.goo.gl/N2vREjw7WJiu7Mwh9' WHERE name ILIKE '%NORZAGARAY%';
UPDATE branches SET address = '101 General Luis, Nagkaisang Nayon, Novaliches, Quezon City', pin_location = 'https://maps.app.goo.gl/3npA5qYRdyAJC7748' WHERE name ILIKE '%NOVALICHES%';
UPDATE branches SET address = 'Ortero Ave St. Brgy. Mabayuan Olongapo City', pin_location = 'https://maps.app.goo.gl/stMc65tx1DXiKEsA7' WHERE name ILIKE '%OLONGAPO%';
UPDATE branches SET address = 'Studio Zen Condominium Pasay Taft 1811 Taft Ave, Pasay City, 1300 Metro Manila', pin_location = 'https://maps.app.goo.gl/mE98ty3DPcwL3KjL9' WHERE name ILIKE '%PASAY%';
UPDATE branches SET address = 'Unit C, 9 Stella Maris Ave. Magbunga Pasig City', pin_location = 'https://maps.app.goo.gl/dVshuDwKTbNPF78Y8' WHERE name ILIKE '%PASIG%';
UPDATE branches SET address = 'BRGY. PALTAO, EB SANTO BUILDING, COR. PEDRO NAVARRO, PULILAN BULACAN', pin_location = 'https://maps.app.goo.gl/spzy436otgD1hCS66' WHERE name ILIKE '%PULILAN%';
UPDATE branches SET address = '36 Rizal Avenue, Sancarlos City, Pangasinan', pin_location = 'https://maps.app.goo.gl/7rdEwzHfXvxD5yLk8' WHERE name ILIKE '%SAN CARLOS%';
UPDATE branches SET address = '1381 Zone 6, Mabini Street, Brgy. Catbangen, San Fernando City, La Union, 2500', pin_location = 'https://share.google/tCS6klKNhoU7wmvu2' WHERE name ILIKE '%SAN FERNANDO%' AND name ILIKE '%LA UNION%';
UPDATE branches SET address = 'Romar Compound, Tagumpay St. San Fernando, 2000 Pampanga Sindalan', pin_location = 'https://maps.app.goo.gl/hsRrgt5MwFzxpXWT6' WHERE name ILIKE '%SAN FERNANDO%' AND name ILIKE '%PAMPANGA%';
UPDATE branches SET address = '134 Tecson St., Sitio San Pedro, Calais, San Miguel Bulacan', pin_location = 'https://maps.app.goo.gl/N4ksz1EmDMsMknzT7' WHERE name ILIKE '%SAN MIGUEL%';
UPDATE branches SET address = 'EPS Building, E. Gonzales Hilot Center, Silang, 4118 Cavite', pin_location = 'https://maps.app.goo.gl/yLuUz51KdBdano169' WHERE name ILIKE '%SILANG%';
UPDATE branches SET address = '682 Rizal Blvd Barangay Labas Santa Rosa Laguna', pin_location = 'https://maps.app.goo.gl/LCPzgN7bJtkY6WWq8' WHERE name ILIKE '%STA ROSA%';
UPDATE branches SET address = 'Bella La Vita Building Purok 2 No.87 San Miguel Santo Tomas Batangas City', pin_location = 'https://maps.app.goo.gl/2fsCh9Z8WNDSaAs18' WHERE name ILIKE '%STO TOMAS%';
UPDATE branches SET address = 'Purok1 Calapacuan Subic Zambales', pin_location = 'https://maps.app.goo.gl/J6xWpLmgMoTN5xGQ7' WHERE name ILIKE '%SUBIC%';
UPDATE branches SET address = 'Brgy Maharlika West, Crisanto M. Delos Reyes Ave. Tagaytay City Cavite', pin_location = 'https://maps.app.goo.gl/L8uth1sLnibuLB9u6' WHERE name ILIKE '%TAGAYTAY%';
UPDATE branches SET address = 'CPG East Avenue Purok 2 Mansasa Tagbilaran City', pin_location = 'https://maps.app.goo.gl/Ya5pyAtrvEsoyvtW7' WHERE name ILIKE '%TAGBILARAN%';
UPDATE branches SET address = '192 M. L. Quezon Avenue Purok 3, New Lower Bicutan Taguig', pin_location = 'https://maps.app.goo.gl/AcD4vEGXNi4VWpKv7' WHERE name ILIKE '%TAGUIG%';
UPDATE branches SET address = '2589 Saint Joseph Avenue Brgy 186 Caloocan City', pin_location = 'https://maps.app.goo.gl/PWmKN7AR9FRh9con8' WHERE name ILIKE '%TALA%';
UPDATE branches SET address = 'Prk. 2 La torre Talavera Nueva Ecija', pin_location = 'https://maps.app.goo.gl/xW9xHdVAWjGjgyrg7' WHERE name ILIKE '%TALAVERA%';
UPDATE branches SET address = 'Citiplaza 1 Commercial Complex, Tandang Sora Ave, Quezon City, 1117 Metro Manila', pin_location = 'https://maps.app.goo.gl/HCza3tarzYrwHTpQ9' WHERE name ILIKE '%TANDANG SORA%';
UPDATE branches SET address = 'Sitio Tambol, 8 Romulo Blvd, Tarlac City, 2300 Tarlac', pin_location = 'https://maps.app.goo.gl/BEVzEQS8gPkj9qzn6' WHERE name ILIKE '%TARLAC%';
UPDATE branches SET address = '001 Manila Roady Brgy San Juan Taytay Rizal', pin_location = 'https://maps.app.goo.gl/7wPjP1KUook5JJpB7' WHERE name ILIKE '%TAYTAY%';
UPDATE branches SET address = '50 Boulevard Street AVG Compound Brgy. May-Iba Teresa Rizal 1880', pin_location = 'https://maps.app.goo.gl/zM6Qcb8ap1hpGtAT9' WHERE name ILIKE '%TERESA%';
UPDATE branches SET address = '628 Raxabago Street Tondo Manila', pin_location = 'https://maps.app.goo.gl/eziW6JMAAUFFF8Le7' WHERE name ILIKE '%TONDO%';
UPDATE branches SET address = 'CHIMMY-ZONETH BUILDING GOVERNOR''S DRIVE TRECE MARTIRES CAVITE', pin_location = 'https://maps.app.goo.gl/rYwBFeeSNfW4CSZd8' WHERE name ILIKE '%TRECE%';
UPDATE branches SET address = 'Two Brothers Diesel Stations, 328 Marcelo H. Del Pilar St. 1440 Metro Manila', pin_location = 'https://waze.com/ul/hwdw58qups' WHERE name ILIKE '%VALENZUELA%';
UPDATE branches SET address = 'Blk1 Lot9 Commercial Highview Homes Congressional Rd Ext Bagumbong Caloocan City', pin_location = 'https://maps.app.goo.gl/sxCPug1HMwyCSSLi8' WHERE name ILIKE '%VICAS%';
